APP_PORT=8080

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=notifier
POSTGRES_USER=notifier
POSTGRES_PASSWORD=notifier

RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
REDIS_ADDR=redis:6379
REDIS_PASSWORD=
REDIS_DB=0

TG_BOT_TOKEN=ваш_токен